// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package cron

import (
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	"github.com/smartcontractkit/cre-sdk-go/cre"
)

type Cron struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

func Trigger(config *Config) cre.Trigger[*Payload, *Payload] {
	configAny := &anypb.Any{}
	_ = anypb.MarshalFrom(configAny, config, proto.MarshalOptions{Deterministic: true})
	return &cronTrigger{

		config: configAny,
	}
}

type cronTrigger struct {
	config *anypb.Any
}

func (*cronTrigger) IsTrigger() {}

func (*cronTrigger) NewT() *Payload {
	return &Payload{}
}

func (c *cronTrigger) CapabilityID() string {
	return "cron-trigger@1.0.0"
}

func (*cronTrigger) Method() string {
	return "Trigger"
}

func (t *cronTrigger) ConfigAsAny() *anypb.Any {
	return t.config
}

func (t *cronTrigger) Adapt(trigger *Payload) (*Payload, error) {
	return trigger, nil
}
