// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc, DO NOT EDIT.

package importclash

import (
	"errors"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	sdkpb "github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/v2/pb"
	"github.com/smartcontractkit/cre-sdk-go/cre"
	"github.com/smartcontractkit/cre-sdk-go/internal_testing/capabilities/importclash/p1"
	"github.com/smartcontractkit/cre-sdk-go/internal_testing/capabilities/importclash/p2"
)

type BasicAction struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

func (c *BasicAction) PerformAction(runtime cre.Runtime, input *p1.Item) cre.Promise[*p2.Item] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*p2.Item](nil, err)
	}
	return cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "import-clash@1.0.0",
		Payload: wrapped,
		Method:  "PerformAction",
	}), func(i *sdkpb.CapabilityResponse) (*p2.Item, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &p2.Item{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}
