// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package solanamock

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"google.golang.org/protobuf/types/known/anypb"

	"github.com/smartcontractkit/cre-sdk-go/capabilities/blockchain/solana"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	"github.com/smartcontractkit/cre-sdk-go/cre/testutils/registry"
)

// avoid unused imports
var _ = registry.Registry{}

func NewClientCapability(ChainSelector uint64, t testing.TB) (*ClientCapability, error) {
	c := &ClientCapability{
		ChainSelector: ChainSelector,
	}
	reg := registry.GetRegistry(t)
	err := reg.RegisterCapability(c)
	return c, err
}

type ClientCapability struct {
	ChainSelector uint64
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	GetAccountInfoWithOpts func(ctx context.Context, input *solana.GetAccountInfoWithOptsRequest) (*solana.GetAccountInfoWithOptsReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	GetBalance func(ctx context.Context, input *solana.GetBalanceRequest) (*solana.GetBalanceReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	GetBlock func(ctx context.Context, input *solana.GetBlockRequest) (*solana.GetBlockReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	GetFeeForMessage func(ctx context.Context, input *solana.GetFeeForMessageRequest) (*solana.GetFeeForMessageReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	GetMultipleAccountsWithOpts func(ctx context.Context, input *solana.GetMultipleAccountsWithOptsRequest) (*solana.GetMultipleAccountsWithOptsReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	GetSignatureStatuses func(ctx context.Context, input *solana.GetSignatureStatusesRequest) (*solana.GetSignatureStatusesReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	GetSlotHeight func(ctx context.Context, input *solana.GetSlotHeightRequest) (*solana.GetSlotHeightReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	GetTransaction func(ctx context.Context, input *solana.GetTransactionRequest) (*solana.GetTransactionReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	WriteReport func(ctx context.Context, input *solana.WriteReportRequest) (*solana.WriteReportReply, error)
}

func (c *ClientCapability) Invoke(ctx context.Context, request *sdkpb.CapabilityRequest) *sdkpb.CapabilityResponse {
	capResp := &sdkpb.CapabilityResponse{}
	switch request.Method {
	case "GetAccountInfoWithOpts":
		input := &solana.GetAccountInfoWithOptsRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.GetAccountInfoWithOpts == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for GetAccountInfoWithOpts"}
			break
		}
		resp, err := c.GetAccountInfoWithOpts(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "GetBalance":
		input := &solana.GetBalanceRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.GetBalance == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for GetBalance"}
			break
		}
		resp, err := c.GetBalance(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "GetBlock":
		input := &solana.GetBlockRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.GetBlock == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for GetBlock"}
			break
		}
		resp, err := c.GetBlock(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "GetFeeForMessage":
		input := &solana.GetFeeForMessageRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.GetFeeForMessage == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for GetFeeForMessage"}
			break
		}
		resp, err := c.GetFeeForMessage(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "GetMultipleAccountsWithOpts":
		input := &solana.GetMultipleAccountsWithOptsRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.GetMultipleAccountsWithOpts == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for GetMultipleAccountsWithOpts"}
			break
		}
		resp, err := c.GetMultipleAccountsWithOpts(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "GetSignatureStatuses":
		input := &solana.GetSignatureStatusesRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.GetSignatureStatuses == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for GetSignatureStatuses"}
			break
		}
		resp, err := c.GetSignatureStatuses(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "GetSlotHeight":
		input := &solana.GetSlotHeightRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.GetSlotHeight == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for GetSlotHeight"}
			break
		}
		resp, err := c.GetSlotHeight(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "GetTransaction":
		input := &solana.GetTransactionRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.GetTransaction == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for GetTransaction"}
			break
		}
		resp, err := c.GetTransaction(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "WriteReport":
		input := &solana.WriteReportRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.WriteReport == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for WriteReport"}
			break
		}
		resp, err := c.WriteReport(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	default:
		capResp.Response = &sdkpb.CapabilityResponse_Error{Error: fmt.Sprintf("method %s not found", request.Method)}
	}

	return capResp
}

func (c *ClientCapability) ID() string {
	return "solana" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0"
}
