// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package confidentialhttpmock

import (
	"context"
	"fmt"
	"testing"

	"google.golang.org/protobuf/types/known/anypb"

	"github.com/smartcontractkit/cre-sdk-go/capabilities/networking/confidentialhttp"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	"github.com/smartcontractkit/cre-sdk-go/cre/testutils/registry"
)

// avoid unused imports
var _ = registry.Registry{}

func NewClientCapability(t testing.TB) (*ClientCapability, error) {
	c := &ClientCapability{}
	reg := registry.GetRegistry(t)
	err := reg.RegisterCapability(c)
	return c, err
}

type ClientCapability struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call
	//SendRequestCapability SendRequest is the new RPC method using the updated types.
	SendRequest func(ctx context.Context, input *confidentialhttp.ConfidentialHTTPRequest) (*confidentialhttp.HTTPResponse, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call
	//SendRequestsCapability Deprecated: Use SendRequest instead.
	SendRequests func(ctx context.Context, input *confidentialhttp.EnclaveActionInput) (*confidentialhttp.HTTPEnclaveResponseData, error)
}

func (c *ClientCapability) Invoke(ctx context.Context, request *sdkpb.CapabilityRequest) *sdkpb.CapabilityResponse {
	capResp := &sdkpb.CapabilityResponse{}
	switch request.Method {
	case "SendRequest":
		input := &confidentialhttp.ConfidentialHTTPRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.SendRequest == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for SendRequest"}
			break
		}
		resp, err := c.SendRequest(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "SendRequests":
		input := &confidentialhttp.EnclaveActionInput{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.SendRequests == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for SendRequests"}
			break
		}
		resp, err := c.SendRequests(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	default:
		capResp.Response = &sdkpb.CapabilityResponse_Error{Error: fmt.Sprintf("method %s not found", request.Method)}
	}

	return capResp
}

func (c *ClientCapability) ID() string {
	return "confidential-http@1.0.0-alpha"
}
