// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package aptosmock

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"google.golang.org/protobuf/types/known/anypb"

	"github.com/smartcontractkit/cre-sdk-go/capabilities/blockchain/aptos"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	"github.com/smartcontractkit/cre-sdk-go/cre/testutils/registry"
)

// avoid unused imports
var _ = registry.Registry{}

func NewClientCapability(ChainSelector uint64, t testing.TB) (*ClientCapability, error) {
	c := &ClientCapability{
		ChainSelector: ChainSelector,
	}
	reg := registry.GetRegistry(t)
	err := reg.RegisterCapability(c)
	return c, err
}

type ClientCapability struct {
	ChainSelector uint64
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	AccountAPTBalance func(ctx context.Context, input *aptos.AccountAPTBalanceRequest) (*aptos.AccountAPTBalanceReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	View func(ctx context.Context, input *aptos.ViewRequest) (*aptos.ViewReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	TransactionByHash func(ctx context.Context, input *aptos.TransactionByHashRequest) (*aptos.TransactionByHashReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	AccountTransactions func(ctx context.Context, input *aptos.AccountTransactionsRequest) (*aptos.AccountTransactionsReply, error)
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call

	WriteReport func(ctx context.Context, input *aptos.WriteReportRequest) (*aptos.WriteReportReply, error)
}

func (c *ClientCapability) Invoke(ctx context.Context, request *sdkpb.CapabilityRequest) *sdkpb.CapabilityResponse {
	capResp := &sdkpb.CapabilityResponse{}
	switch request.Method {
	case "AccountAPTBalance":
		input := &aptos.AccountAPTBalanceRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.AccountAPTBalance == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for AccountAPTBalance"}
			break
		}
		resp, err := c.AccountAPTBalance(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "View":
		input := &aptos.ViewRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.View == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for View"}
			break
		}
		resp, err := c.View(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "TransactionByHash":
		input := &aptos.TransactionByHashRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.TransactionByHash == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for TransactionByHash"}
			break
		}
		resp, err := c.TransactionByHash(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "AccountTransactions":
		input := &aptos.AccountTransactionsRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.AccountTransactions == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for AccountTransactions"}
			break
		}
		resp, err := c.AccountTransactions(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	case "WriteReport":
		input := &aptos.WriteReportRequest{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.WriteReport == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for WriteReport"}
			break
		}
		resp, err := c.WriteReport(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	default:
		capResp.Response = &sdkpb.CapabilityResponse_Error{Error: fmt.Sprintf("method %s not found", request.Method)}
	}

	return capResp
}

func (c *ClientCapability) ID() string {
	return "aptos" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0"
}
