// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package confidentialhttp

import (
	"errors"
	"log/slog"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	"github.com/smartcontractkit/cre-sdk-go/cre"
)

type Client struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

type SendRequestser struct {
	client      *Client
	nodeRuntime cre.NodeRuntime
}

func (c *SendRequestser) SendRequests(input *EnclaveActionInput) cre.Promise[*HTTPEnclaveResponseData] {
	return c.client.SendRequests(c.nodeRuntime, input)
}

// SendRequests Allows usage of `SendRequestser` with Byzantine fault tolerance.
func SendRequests[C, T any](
	config C,
	runtime cre.Runtime,
	client *Client,
	fn func(config C, logger *slog.Logger, sendRequestser *SendRequestser) (T, error),
	ca cre.ConsensusAggregation[T]) cre.Promise[T] {
	wrapped := func(config C, nodeRuntime cre.NodeRuntime) (T, error) {
		sendRequestser := SendRequestser{client: client, nodeRuntime: nodeRuntime}
		return fn(config, runtime.Logger(), &sendRequestser)
	}

	return cre.RunInNodeMode(config, runtime, wrapped, ca)
}

func (c *Client) SendRequests(runtime cre.NodeRuntime, input *EnclaveActionInput) cre.Promise[*HTTPEnclaveResponseData] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*HTTPEnclaveResponseData](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "confidential-http@1.0.0-alpha",
		Payload: wrapped,
		Method:  "SendRequests",
	}), func(i *sdkpb.CapabilityResponse) (*HTTPEnclaveResponseData, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &HTTPEnclaveResponseData{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}
