// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package confidentialhttp

import (
	"errors"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	"github.com/smartcontractkit/cre-sdk-go/cre"
)

type Client struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

func (c *Client) SendRequest(runtime cre.Runtime, input *ConfidentialHTTPRequest) cre.Promise[*HTTPResponse] {
	return c.sendRequest(runtime, input)
}

// SendRequestInTee is the same as SendRequest but accepts a cre.TeeRuntime.
func (c *Client) SendRequestInTee(runtime cre.TeeRuntime, input *ConfidentialHTTPRequest) cre.Promise[*HTTPResponse] {
	return c.sendRequest(runtime, input)
}

func (c *Client) sendRequest(runtime cre.RuntimeBase, input *ConfidentialHTTPRequest) cre.Promise[*HTTPResponse] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*HTTPResponse](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "confidential-http@1.0.0-alpha",
		Payload: wrapped,
		Method:  "SendRequest",
	}), func(i *sdkpb.CapabilityResponse) (*HTTPResponse, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &HTTPResponse{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}
