// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc, DO NOT EDIT.

package basicactionmock

import (
	"context"
	"fmt"
	"testing"

	"google.golang.org/protobuf/types/known/anypb"

	"github.com/smartcontractkit/cre-sdk-go/internal_testing/capabilities/basicaction"

	sdkpb "github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/v2/pb"
	"github.com/smartcontractkit/cre-sdk-go/cre/testutils/registry"
)

// avoid unused imports
var _ = registry.Registry{}

// BasicActionCapability This action server for testing purposes only.
func NewBasicActionCapability(t testing.TB) (*BasicActionCapability, error) { //BasicActionCapability This comment tests the generator's ability to handle comments.
	c := &BasicActionCapability{}
	reg := registry.GetRegistry(t)
	err := reg.RegisterCapability(c)
	return c, err
}

// BasicActionCapability This action server for testing purposes only.
type BasicActionCapability struct { //BasicActionCapability This comment tests the generator's ability to handle comments.
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 add the default to the call
	//PerformActionCapability This comment tests the generator's ability to handle leading comments on methods.
	PerformAction func(ctx context.Context, input *basicaction.Inputs) (*basicaction.Outputs, error) //PerformActionCapability This comment tests the generator's ability to handle trailing comments on methods.
}

func (c *BasicActionCapability) Invoke(ctx context.Context, request *sdkpb.CapabilityRequest) *sdkpb.CapabilityResponse {
	capResp := &sdkpb.CapabilityResponse{}
	switch request.Method {
	case "PerformAction":
		input := &basicaction.Inputs{}
		if err := request.Payload.UnmarshalTo(input); err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			break
		}

		if c.PerformAction == nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: "no stub provided for PerformAction"}
			break
		}
		resp, err := c.PerformAction(ctx, input)
		if err != nil {
			capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
		} else {
			payload, err := anypb.New(resp)
			if err == nil {
				capResp.Response = &sdkpb.CapabilityResponse_Payload{Payload: payload}
			} else {
				capResp.Response = &sdkpb.CapabilityResponse_Error{Error: err.Error()}
			}
		}
	default:
		capResp.Response = &sdkpb.CapabilityResponse_Error{Error: fmt.Sprintf("method %s not found", request.Method)}
	}

	return capResp
}

func (c *BasicActionCapability) ID() string {
	return "basic-test-action@1.0.0"
}
