// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package nodeaction

import (
	"errors"
	"log/slog"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	"github.com/smartcontractkit/cre-sdk-go/cre"
)

type BasicAction struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

type PerformActioner struct {
	client      *BasicAction
	nodeRuntime cre.NodeRuntime
}

func (c *PerformActioner) PerformAction(input *NodeInputs) cre.Promise[*NodeOutputs] {
	return c.client.PerformAction(c.nodeRuntime, input)
}

// PerformAction Allows usage of `PerformActioner` with Byzantine fault tolerance.
func PerformAction[C, T any](
	config C,
	runtime cre.Runtime,
	client *BasicAction,
	fn func(config C, logger *slog.Logger, performActioner *PerformActioner) (T, error),
	ca cre.ConsensusAggregation[T]) cre.Promise[T] {
	wrapped := func(config C, nodeRuntime cre.NodeRuntime) (T, error) {
		performActioner := PerformActioner{client: client, nodeRuntime: nodeRuntime}
		return fn(config, runtime.Logger(), &performActioner)
	}

	return cre.RunInNodeMode(config, runtime, wrapped, ca)
}

func (c *BasicAction) PerformAction(runtime cre.NodeRuntime, input *NodeInputs) cre.Promise[*NodeOutputs] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*NodeOutputs](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "basic-test-node-action@1.0.0",
		Payload: wrapped,
		Method:  "PerformAction",
	}), func(i *sdkpb.CapabilityResponse) (*NodeOutputs, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &NodeOutputs{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}
