// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package actionandtrigger

import (
	"errors"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	caperrors "github.com/smartcontractkit/cre-sdk-go/capabilities/errors"
	"github.com/smartcontractkit/cre-sdk-go/cre"
)

type Basic struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

func (c *Basic) Action(runtime cre.Runtime, input *Input) cre.Promise[*Output] {
	return c.action(runtime, input)
}

func (c *Basic) action(runtime cre.RuntimeBase, input *Input) cre.Promise[*Output] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*Output](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "basic-test-action-trigger@1.0.0",
		Payload: wrapped,
		Method:  "Action",
	}), func(i *sdkpb.CapabilityResponse) (*Output, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, caperrors.DeserializeErrorFromString(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &Output{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

func Trigger(config *Config) cre.Trigger[*TriggerEvent, *TriggerEvent] {
	configAny := &anypb.Any{}
	_ = anypb.MarshalFrom(configAny, config, proto.MarshalOptions{Deterministic: true})
	return &basicTrigger{

		config: configAny,
	}
}

type basicTrigger struct {
	config *anypb.Any
}

func (*basicTrigger) IsTrigger() {}

func (*basicTrigger) NewT() *TriggerEvent {
	return &TriggerEvent{}
}

func (c *basicTrigger) CapabilityID() string {
	return "basic-test-action-trigger@1.0.0"
}

func (*basicTrigger) Method() string {
	return "Trigger"
}

func (t *basicTrigger) ConfigAsAny() *anypb.Any {
	return t.config
}

func (t *basicTrigger) Adapt(trigger *TriggerEvent) (*TriggerEvent, error) {
	return trigger, nil
}

type BasicRestrictor struct {
}

func (c *BasicRestrictor) LimitAction(maxCalls int32) *sdkpb.CapabilityRestriction {
	return &sdkpb.CapabilityRestriction{
		Restriction: &sdkpb.CapabilityRestriction_Method{
			Method: &sdkpb.MethodRestriction{
				Id:       "basic-test-action-trigger@1.0.0",
				Method:   "Action",
				MaxCalls: maxCalls,
			},
		},
	}
}
