// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package solana

import (
	"errors"
	"fmt"
	"strconv"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	"github.com/smartcontractkit/cre-sdk-go/cre"
)

type Client struct {
	ChainSelector uint64
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

type WriteCreReportRequest struct {
	RemainingAccounts []*AccountMeta // accounts that are required by the receiver to accept the report

	Receiver []byte // 32 bytes receiver

	ComputeConfig *ComputeConfig

	Report *cre.Report
}

// X_GeneratedCodeOnly_WrapWriteCreReportRequest is only meant to be used by the generated code.
func X_GeneratedCodeOnly_Wrap_WriteCreReportRequest(i *WriteReportRequest) (*WriteCreReportRequest, error) { //nolint

	remainingAccounts := i.RemainingAccounts

	receiver := i.Receiver

	computeConfig := i.ComputeConfig

	report, err := cre.X_GeneratedCodeOnly_WrapReport(i.Report)
	if err != nil {
		return nil, fmt.Errorf("failed to wrap report for field %s: %w", "Report", err)
	}

	return &WriteCreReportRequest{

		RemainingAccounts: remainingAccounts,
		Receiver:          receiver,
		ComputeConfig:     computeConfig,
		Report:            report,
	}, nil
}

// X_GeneratedCodeOnly_Unwrap is only meant to be used by the generated code.
func (i *WriteCreReportRequest) X_GeneratedCodeOnly_Unwrap() *WriteReportRequest { //nolint
	return &WriteReportRequest{

		RemainingAccounts: i.RemainingAccounts,
		Receiver:          i.Receiver,
		ComputeConfig:     i.ComputeConfig,
		Report:            i.Report.X_GeneratedCodeOnly_Unwrap(),
	}
}

func (c *Client) WriteReport(runtime cre.Runtime, input *WriteCreReportRequest) cre.Promise[*WriteReportReply] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input.X_GeneratedCodeOnly_Unwrap(), proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*WriteReportReply](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "solana" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
		Payload: wrapped,
		Method:  "WriteReport",
	}), func(i *sdkpb.CapabilityResponse) (*WriteReportReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &WriteReportReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

const SolanaDevnet = 16423721717087811551

const SolanaMainnet = 124615329519749607

func ChainSelectorFromName(name string) (uint64, error) {
	switch name {
	case "solana-devnet":
		return SolanaDevnet, nil
	case "solana-mainnet":
		return SolanaMainnet, nil
	default:
		return 0, errors.New("unknown ChainSelector" + name)
	}
}
