// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: capabilities/blockchain/solana/v1alpha/client.proto

package solana

import (
	sdk "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	_ "github.com/smartcontractkit/chainlink-protos/cre/go/tools/generator"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction execution status returned by submitters/simulations.
type TxStatus int32

const (
	TxStatus_TX_STATUS_FATAL   TxStatus = 0 // unrecoverable failure
	TxStatus_TX_STATUS_ABORTED TxStatus = 1 // not executed / dropped
	TxStatus_TX_STATUS_SUCCESS TxStatus = 2 // executed successfully
)

// Enum value maps for TxStatus.
var (
	TxStatus_name = map[int32]string{
		0: "TX_STATUS_FATAL",
		1: "TX_STATUS_ABORTED",
		2: "TX_STATUS_SUCCESS",
	}
	TxStatus_value = map[string]int32{
		"TX_STATUS_FATAL":   0,
		"TX_STATUS_ABORTED": 1,
		"TX_STATUS_SUCCESS": 2,
	}
)

func (x TxStatus) Enum() *TxStatus {
	p := new(TxStatus)
	*p = x
	return p
}

func (x TxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_capabilities_blockchain_solana_v1alpha_client_proto_enumTypes[0].Descriptor()
}

func (TxStatus) Type() protoreflect.EnumType {
	return &file_capabilities_blockchain_solana_v1alpha_client_proto_enumTypes[0]
}

func (x TxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxStatus.Descriptor instead.
func (TxStatus) EnumDescriptor() ([]byte, []int) {
	return file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescGZIP(), []int{0}
}

type ReceiverContractExecutionStatus int32

const (
	ReceiverContractExecutionStatus_RECEIVER_CONTRACT_EXECUTION_STATUS_SUCCESS  ReceiverContractExecutionStatus = 0
	ReceiverContractExecutionStatus_RECEIVER_CONTRACT_EXECUTION_STATUS_REVERTED ReceiverContractExecutionStatus = 1
)

// Enum value maps for ReceiverContractExecutionStatus.
var (
	ReceiverContractExecutionStatus_name = map[int32]string{
		0: "RECEIVER_CONTRACT_EXECUTION_STATUS_SUCCESS",
		1: "RECEIVER_CONTRACT_EXECUTION_STATUS_REVERTED",
	}
	ReceiverContractExecutionStatus_value = map[string]int32{
		"RECEIVER_CONTRACT_EXECUTION_STATUS_SUCCESS":  0,
		"RECEIVER_CONTRACT_EXECUTION_STATUS_REVERTED": 1,
	}
)

func (x ReceiverContractExecutionStatus) Enum() *ReceiverContractExecutionStatus {
	p := new(ReceiverContractExecutionStatus)
	*p = x
	return p
}

func (x ReceiverContractExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiverContractExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_capabilities_blockchain_solana_v1alpha_client_proto_enumTypes[1].Descriptor()
}

func (ReceiverContractExecutionStatus) Type() protoreflect.EnumType {
	return &file_capabilities_blockchain_solana_v1alpha_client_proto_enumTypes[1]
}

func (x ReceiverContractExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiverContractExecutionStatus.Descriptor instead.
func (ReceiverContractExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescGZIP(), []int{1}
}

// Compute budget configuration when submitting txs.
type ComputeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComputeLimit  uint32                 `protobuf:"varint,1,opt,name=compute_limit,json=computeLimit,proto3" json:"compute_limit,omitempty"` // max CUs (approx per-tx limit)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeConfig) Reset() {
	*x = ComputeConfig{}
	mi := &file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeConfig) ProtoMessage() {}

func (x *ComputeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeConfig.ProtoReflect.Descriptor instead.
func (*ComputeConfig) Descriptor() ([]byte, []int) {
	return file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeConfig) GetComputeLimit() uint32 {
	if x != nil {
		return x.ComputeLimit
	}
	return 0
}

// All metas are non-signers.
type AccountMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`     // 32 bytes account public key
	IsWritable    bool                   `protobuf:"varint,2,opt,name=is_writable,json=isWritable,proto3" json:"is_writable,omitempty"` // write flag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountMeta) Reset() {
	*x = AccountMeta{}
	mi := &file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMeta) ProtoMessage() {}

func (x *AccountMeta) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountMeta.ProtoReflect.Descriptor instead.
func (*AccountMeta) Descriptor() ([]byte, []int) {
	return file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescGZIP(), []int{1}
}

func (x *AccountMeta) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AccountMeta) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

type WriteReportRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RemainingAccounts []*AccountMeta         `protobuf:"bytes,1,rep,name=remaining_accounts,json=remainingAccounts,proto3" json:"remaining_accounts,omitempty"` // accounts that are required by the receiver to accept the report
	Receiver          []byte                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`                                            // 32 bytes receiver
	ComputeConfig     *ComputeConfig         `protobuf:"bytes,3,opt,name=compute_config,json=computeConfig,proto3,oneof" json:"compute_config,omitempty"`
	Report            *sdk.ReportResponse    `protobuf:"bytes,4,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WriteReportRequest) Reset() {
	*x = WriteReportRequest{}
	mi := &file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportRequest) ProtoMessage() {}

func (x *WriteReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportRequest.ProtoReflect.Descriptor instead.
func (*WriteReportRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescGZIP(), []int{2}
}

func (x *WriteReportRequest) GetRemainingAccounts() []*AccountMeta {
	if x != nil {
		return x.RemainingAccounts
	}
	return nil
}

func (x *WriteReportRequest) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *WriteReportRequest) GetComputeConfig() *ComputeConfig {
	if x != nil {
		return x.ComputeConfig
	}
	return nil
}

func (x *WriteReportRequest) GetReport() *sdk.ReportResponse {
	if x != nil {
		return x.Report
	}
	return nil
}

type WriteReportReply struct {
	state                           protoimpl.MessageState           `protogen:"open.v1"`
	TxStatus                        TxStatus                         `protobuf:"varint,1,opt,name=tx_status,json=txStatus,proto3,enum=capabilities.blockchain.solana.v1alpha.TxStatus" json:"tx_status,omitempty"`
	ReceiverContractExecutionStatus *ReceiverContractExecutionStatus `protobuf:"varint,2,opt,name=receiver_contract_execution_status,json=receiverContractExecutionStatus,proto3,enum=capabilities.blockchain.solana.v1alpha.ReceiverContractExecutionStatus,oneof" json:"receiver_contract_execution_status,omitempty"`
	TxSignature                     []byte                           `protobuf:"bytes,3,opt,name=tx_signature,json=txSignature,proto3,oneof" json:"tx_signature,omitempty"`
	TransactionFee                  *uint64                          `protobuf:"varint,4,opt,name=transaction_fee,json=transactionFee,proto3,oneof" json:"transaction_fee,omitempty"`
	ErrorMessage                    *string                          `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *WriteReportReply) Reset() {
	*x = WriteReportReply{}
	mi := &file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportReply) ProtoMessage() {}

func (x *WriteReportReply) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportReply.ProtoReflect.Descriptor instead.
func (*WriteReportReply) Descriptor() ([]byte, []int) {
	return file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescGZIP(), []int{3}
}

func (x *WriteReportReply) GetTxStatus() TxStatus {
	if x != nil {
		return x.TxStatus
	}
	return TxStatus_TX_STATUS_FATAL
}

func (x *WriteReportReply) GetReceiverContractExecutionStatus() ReceiverContractExecutionStatus {
	if x != nil && x.ReceiverContractExecutionStatus != nil {
		return *x.ReceiverContractExecutionStatus
	}
	return ReceiverContractExecutionStatus_RECEIVER_CONTRACT_EXECUTION_STATUS_SUCCESS
}

func (x *WriteReportReply) GetTxSignature() []byte {
	if x != nil {
		return x.TxSignature
	}
	return nil
}

func (x *WriteReportReply) GetTransactionFee() uint64 {
	if x != nil && x.TransactionFee != nil {
		return *x.TransactionFee
	}
	return 0
}

func (x *WriteReportReply) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_capabilities_blockchain_solana_v1alpha_client_proto protoreflect.FileDescriptor

const file_capabilities_blockchain_solana_v1alpha_client_proto_rawDesc = "" +
	"\n" +
	"3capabilities/blockchain/solana/v1alpha/client.proto\x12&capabilities.blockchain.solana.v1alpha\x1a\x15sdk/v1alpha/sdk.proto\x1a*tools/generator/v1alpha/cre_metadata.proto\"4\n" +
	"\rComputeConfig\x12#\n" +
	"\rcompute_limit\x18\x01 \x01(\rR\fcomputeLimit\"M\n" +
	"\vAccountMeta\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vis_writable\x18\x02 \x01(\bR\n" +
	"isWritable\"\xbf\x02\n" +
	"\x12WriteReportRequest\x12b\n" +
	"\x12remaining_accounts\x18\x01 \x03(\v23.capabilities.blockchain.solana.v1alpha.AccountMetaR\x11remainingAccounts\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\fR\breceiver\x12a\n" +
	"\x0ecompute_config\x18\x03 \x01(\v25.capabilities.blockchain.solana.v1alpha.ComputeConfigH\x00R\rcomputeConfig\x88\x01\x01\x123\n" +
	"\x06report\x18\x04 \x01(\v2\x1b.sdk.v1alpha.ReportResponseR\x06reportB\x11\n" +
	"\x0f_compute_config\"\xdb\x03\n" +
	"\x10WriteReportReply\x12M\n" +
	"\ttx_status\x18\x01 \x01(\x0e20.capabilities.blockchain.solana.v1alpha.TxStatusR\btxStatus\x12\x99\x01\n" +
	"\"receiver_contract_execution_status\x18\x02 \x01(\x0e2G.capabilities.blockchain.solana.v1alpha.ReceiverContractExecutionStatusH\x00R\x1freceiverContractExecutionStatus\x88\x01\x01\x12&\n" +
	"\ftx_signature\x18\x03 \x01(\fH\x01R\vtxSignature\x88\x01\x01\x12,\n" +
	"\x0ftransaction_fee\x18\x04 \x01(\x04H\x02R\x0etransactionFee\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x03R\ferrorMessage\x88\x01\x01B%\n" +
	"#_receiver_contract_execution_statusB\x0f\n" +
	"\r_tx_signatureB\x12\n" +
	"\x10_transaction_feeB\x10\n" +
	"\x0e_error_message*M\n" +
	"\bTxStatus\x12\x13\n" +
	"\x0fTX_STATUS_FATAL\x10\x00\x12\x15\n" +
	"\x11TX_STATUS_ABORTED\x10\x01\x12\x15\n" +
	"\x11TX_STATUS_SUCCESS\x10\x02*\x82\x01\n" +
	"\x1fReceiverContractExecutionStatus\x12.\n" +
	"*RECEIVER_CONTRACT_EXECUTION_STATUS_SUCCESS\x10\x00\x12/\n" +
	"+RECEIVER_CONTRACT_EXECUTION_STATUS_REVERTED\x10\x012\xf1\x01\n" +
	"\x06Client\x12\x83\x01\n" +
	"\vWriteReport\x12:.capabilities.blockchain.solana.v1alpha.WriteReportRequest\x1a8.capabilities.blockchain.solana.v1alpha.WriteReportReply\x1aa\x82\xb5\x18]\b\x01\x12\fsolana@1.0.0\x1aK\n" +
	"\rChainSelector\x12:\x128\n" +
	"\x1a\n" +
	"\rsolana-devnet\x10\xdf\uf327\xa9\xfc\xb1\xf6\xe3\x01\n" +
	"\x1a\n" +
	"\x0esolana-mainnet\x10\xe7\x93ߌ\xb6\x9f\xae\xdd\x01b\x06proto3"

var (
	file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescOnce sync.Once
	file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescData []byte
)

func file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescGZIP() []byte {
	file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescOnce.Do(func() {
		file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capabilities_blockchain_solana_v1alpha_client_proto_rawDesc), len(file_capabilities_blockchain_solana_v1alpha_client_proto_rawDesc)))
	})
	return file_capabilities_blockchain_solana_v1alpha_client_proto_rawDescData
}

var file_capabilities_blockchain_solana_v1alpha_client_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_capabilities_blockchain_solana_v1alpha_client_proto_goTypes = []any{
	(TxStatus)(0),                        // 0: capabilities.blockchain.solana.v1alpha.TxStatus
	(ReceiverContractExecutionStatus)(0), // 1: capabilities.blockchain.solana.v1alpha.ReceiverContractExecutionStatus
	(*ComputeConfig)(nil),                // 2: capabilities.blockchain.solana.v1alpha.ComputeConfig
	(*AccountMeta)(nil),                  // 3: capabilities.blockchain.solana.v1alpha.AccountMeta
	(*WriteReportRequest)(nil),           // 4: capabilities.blockchain.solana.v1alpha.WriteReportRequest
	(*WriteReportReply)(nil),             // 5: capabilities.blockchain.solana.v1alpha.WriteReportReply
	(*sdk.ReportResponse)(nil),           // 6: sdk.v1alpha.ReportResponse
}
var file_capabilities_blockchain_solana_v1alpha_client_proto_depIdxs = []int32{
	3, // 0: capabilities.blockchain.solana.v1alpha.WriteReportRequest.remaining_accounts:type_name -> capabilities.blockchain.solana.v1alpha.AccountMeta
	2, // 1: capabilities.blockchain.solana.v1alpha.WriteReportRequest.compute_config:type_name -> capabilities.blockchain.solana.v1alpha.ComputeConfig
	6, // 2: capabilities.blockchain.solana.v1alpha.WriteReportRequest.report:type_name -> sdk.v1alpha.ReportResponse
	0, // 3: capabilities.blockchain.solana.v1alpha.WriteReportReply.tx_status:type_name -> capabilities.blockchain.solana.v1alpha.TxStatus
	1, // 4: capabilities.blockchain.solana.v1alpha.WriteReportReply.receiver_contract_execution_status:type_name -> capabilities.blockchain.solana.v1alpha.ReceiverContractExecutionStatus
	4, // 5: capabilities.blockchain.solana.v1alpha.Client.WriteReport:input_type -> capabilities.blockchain.solana.v1alpha.WriteReportRequest
	5, // 6: capabilities.blockchain.solana.v1alpha.Client.WriteReport:output_type -> capabilities.blockchain.solana.v1alpha.WriteReportReply
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_capabilities_blockchain_solana_v1alpha_client_proto_init() }
func file_capabilities_blockchain_solana_v1alpha_client_proto_init() {
	if File_capabilities_blockchain_solana_v1alpha_client_proto != nil {
		return
	}
	file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[2].OneofWrappers = []any{}
	file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capabilities_blockchain_solana_v1alpha_client_proto_rawDesc), len(file_capabilities_blockchain_solana_v1alpha_client_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capabilities_blockchain_solana_v1alpha_client_proto_goTypes,
		DependencyIndexes: file_capabilities_blockchain_solana_v1alpha_client_proto_depIdxs,
		EnumInfos:         file_capabilities_blockchain_solana_v1alpha_client_proto_enumTypes,
		MessageInfos:      file_capabilities_blockchain_solana_v1alpha_client_proto_msgTypes,
	}.Build()
	File_capabilities_blockchain_solana_v1alpha_client_proto = out.File
	file_capabilities_blockchain_solana_v1alpha_client_proto_goTypes = nil
	file_capabilities_blockchain_solana_v1alpha_client_proto_depIdxs = nil
}
