// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc, DO NOT EDIT.

package basicaction

import (
	"errors"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	sdkpb "github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/v2/pb"
	"github.com/smartcontractkit/cre-sdk-go/cre"
)

// BasicActionCapability This action server for testing purposes only.
type BasicAction struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

// <no value>Capability This comment tests the generator's ability to handle leading comments on methods.
func (c *BasicAction) PerformAction(runtime cre.Runtime, input *Inputs) cre.Promise[*Outputs] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*Outputs](nil, err)
	}
	return cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "basic-test-action@1.0.0",
		Payload: wrapped,
		Method:  "PerformAction",
	}), func(i *sdkpb.CapabilityResponse) (*Outputs, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, errors.New(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &Outputs{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})
}
