// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package aptos

import (
	"errors"
	"fmt"
	"strconv"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	caperrors "github.com/smartcontractkit/cre-sdk-go/capabilities/errors"
	"github.com/smartcontractkit/cre-sdk-go/cre"
)

type Client struct {
	ChainSelector uint64
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

func (c *Client) AccountAPTBalance(runtime cre.Runtime, input *AccountAPTBalanceRequest) cre.Promise[*AccountAPTBalanceReply] {
	return c.accountAPTBalance(runtime, input)
}

func (c *Client) accountAPTBalance(runtime cre.RuntimeBase, input *AccountAPTBalanceRequest) cre.Promise[*AccountAPTBalanceReply] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*AccountAPTBalanceReply](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "aptos" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
		Payload: wrapped,
		Method:  "AccountAPTBalance",
	}), func(i *sdkpb.CapabilityResponse) (*AccountAPTBalanceReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, caperrors.DeserializeErrorFromString(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &AccountAPTBalanceReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

func (c *Client) View(runtime cre.Runtime, input *ViewRequest) cre.Promise[*ViewReply] {
	return c.view(runtime, input)
}

func (c *Client) view(runtime cre.RuntimeBase, input *ViewRequest) cre.Promise[*ViewReply] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*ViewReply](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "aptos" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
		Payload: wrapped,
		Method:  "View",
	}), func(i *sdkpb.CapabilityResponse) (*ViewReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, caperrors.DeserializeErrorFromString(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &ViewReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

func (c *Client) TransactionByHash(runtime cre.Runtime, input *TransactionByHashRequest) cre.Promise[*TransactionByHashReply] {
	return c.transactionByHash(runtime, input)
}

func (c *Client) transactionByHash(runtime cre.RuntimeBase, input *TransactionByHashRequest) cre.Promise[*TransactionByHashReply] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*TransactionByHashReply](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "aptos" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
		Payload: wrapped,
		Method:  "TransactionByHash",
	}), func(i *sdkpb.CapabilityResponse) (*TransactionByHashReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, caperrors.DeserializeErrorFromString(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &TransactionByHashReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

func (c *Client) AccountTransactions(runtime cre.Runtime, input *AccountTransactionsRequest) cre.Promise[*AccountTransactionsReply] {
	return c.accountTransactions(runtime, input)
}

func (c *Client) accountTransactions(runtime cre.RuntimeBase, input *AccountTransactionsRequest) cre.Promise[*AccountTransactionsReply] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*AccountTransactionsReply](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "aptos" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
		Payload: wrapped,
		Method:  "AccountTransactions",
	}), func(i *sdkpb.CapabilityResponse) (*AccountTransactionsReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, caperrors.DeserializeErrorFromString(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &AccountTransactionsReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

type WriteCreReportRequest struct {
	Receiver []byte // 32-byte Aptos account address of the receiver module

	GasConfig *GasConfig // optional gas configuration

	Report *cre.Report // signed report from consensus

}

// X_GeneratedCodeOnly_WrapWriteCreReportRequest is only meant to be used by the generated code.
func X_GeneratedCodeOnly_Wrap_WriteCreReportRequest(i *WriteReportRequest) (*WriteCreReportRequest, error) { //nolint

	receiver := i.Receiver

	gasConfig := i.GasConfig

	report, err := cre.X_GeneratedCodeOnly_WrapReport(i.Report)
	if err != nil {
		return nil, fmt.Errorf("failed to wrap report for field %s: %w", "Report", err)
	}

	return &WriteCreReportRequest{

		Receiver:  receiver,
		GasConfig: gasConfig,
		Report:    report,
	}, nil
}

// X_GeneratedCodeOnly_Unwrap is only meant to be used by the generated code.
func (i *WriteCreReportRequest) X_GeneratedCodeOnly_Unwrap() *WriteReportRequest { //nolint
	return &WriteReportRequest{

		Receiver:  i.Receiver,
		GasConfig: i.GasConfig,
		Report:    i.Report.X_GeneratedCodeOnly_Unwrap(),
	}
}

func (c *Client) WriteReport(runtime cre.Runtime, input *WriteCreReportRequest) cre.Promise[*WriteReportReply] {
	return c.writeReport(runtime, input)
}

func (c *Client) writeReport(runtime cre.RuntimeBase, input *WriteCreReportRequest) cre.Promise[*WriteReportReply] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input.X_GeneratedCodeOnly_Unwrap(), proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*WriteReportReply](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "aptos" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
		Payload: wrapped,
		Method:  "WriteReport",
	}), func(i *sdkpb.CapabilityResponse) (*WriteReportReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, caperrors.DeserializeErrorFromString(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &WriteReportReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

const AptosMainnet = 4741433654826277614

const AptosTestnet = 743186221051783445

func ChainSelectorFromName(name string) (uint64, error) {
	switch name {
	case "aptos-mainnet":
		return AptosMainnet, nil
	case "aptos-testnet":
		return AptosTestnet, nil
	default:
		return 0, errors.New("unknown ChainSelector" + name)
	}
}
