// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc, DO NOT EDIT.

package basictrigger

import (
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	"github.com/smartcontractkit/cre-sdk-go/cre"
)

type Basic struct {
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

func Trigger(config *Config) cre.Trigger[*Outputs, *Outputs] {
	configAny := &anypb.Any{}
	_ = anypb.MarshalFrom(configAny, config, proto.MarshalOptions{Deterministic: true})
	return &basicTrigger{

		config: configAny,
	}
}

type basicTrigger struct {
	config *anypb.Any
}

func (*basicTrigger) IsTrigger() {}

func (*basicTrigger) NewT() *Outputs {
	return &Outputs{}
}

func (c *basicTrigger) CapabilityID() string {
	return "basic-test-trigger@1.0.0"
}

func (*basicTrigger) Method() string {
	return "Trigger"
}

func (t *basicTrigger) ConfigAsAny() *anypb.Any {
	return t.config
}

func (t *basicTrigger) Adapt(trigger *Outputs) (*Outputs, error) {
	return trigger, nil
}
