// Code generated by github.com/smartcontractkit/cre-sdk-go/generator/protoc-gen-cre, DO NOT EDIT.

package stellar

import (
	"errors"
	"fmt"
	"strconv"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	sdkpb "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"
	caperrors "github.com/smartcontractkit/cre-sdk-go/capabilities/errors"
	"github.com/smartcontractkit/cre-sdk-go/cre"
)

type Client struct {
	ChainSelector uint64
	// TODO: https://smartcontract-it.atlassian.net/browse/CAPPL-799 allow defaults for capabilities
}

func (c *Client) GetLatestLedger(runtime cre.Runtime, input *GetLatestLedgerRequest) cre.Promise[*GetLatestLedgerResponse] {
	return c.getLatestLedger(runtime, input)
}

func (c *Client) getLatestLedger(runtime cre.RuntimeBase, input *GetLatestLedgerRequest) cre.Promise[*GetLatestLedgerResponse] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*GetLatestLedgerResponse](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "stellar" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
		Payload: wrapped,
		Method:  "GetLatestLedger",
	}), func(i *sdkpb.CapabilityResponse) (*GetLatestLedgerResponse, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, caperrors.DeserializeErrorFromString(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &GetLatestLedgerResponse{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

func (c *Client) ReadContract(runtime cre.Runtime, input *ReadContractRequest) cre.Promise[*ReadContractResponse] {
	return c.readContract(runtime, input)
}

func (c *Client) readContract(runtime cre.RuntimeBase, input *ReadContractRequest) cre.Promise[*ReadContractResponse] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input, proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*ReadContractResponse](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "stellar" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
		Payload: wrapped,
		Method:  "ReadContract",
	}), func(i *sdkpb.CapabilityResponse) (*ReadContractResponse, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, caperrors.DeserializeErrorFromString(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &ReadContractResponse{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

type WriteCreReportRequest struct {
	ContractId string // Stellar contract address (C… StrKey)

	Report *cre.Report // signed report from consensus

}

// X_GeneratedCodeOnly_WrapWriteCreReportRequest is only meant to be used by the generated code.
func X_GeneratedCodeOnly_Wrap_WriteCreReportRequest(i *WriteReportRequest) (*WriteCreReportRequest, error) { //nolint

	contractId := i.ContractId

	report, err := cre.X_GeneratedCodeOnly_WrapReport(i.Report)
	if err != nil {
		return nil, fmt.Errorf("failed to wrap report for field %s: %w", "Report", err)
	}

	return &WriteCreReportRequest{

		ContractId: contractId,
		Report:     report,
	}, nil
}

// X_GeneratedCodeOnly_Unwrap is only meant to be used by the generated code.
func (i *WriteCreReportRequest) X_GeneratedCodeOnly_Unwrap() *WriteReportRequest { //nolint
	return &WriteReportRequest{

		ContractId: i.ContractId,
		Report:     i.Report.X_GeneratedCodeOnly_Unwrap(),
	}
}

func (c *Client) WriteReport(runtime cre.Runtime, input *WriteCreReportRequest) cre.Promise[*WriteReportReply] {
	return c.writeReport(runtime, input)
}

func (c *Client) writeReport(runtime cre.RuntimeBase, input *WriteCreReportRequest) cre.Promise[*WriteReportReply] {
	wrapped := &anypb.Any{}
	err := anypb.MarshalFrom(wrapped, input.X_GeneratedCodeOnly_Unwrap(), proto.MarshalOptions{Deterministic: true})
	if err != nil {
		return cre.PromiseFromResult[*WriteReportReply](nil, err)
	}

	capCallResponse := cre.Then(runtime.CallCapability(&sdkpb.CapabilityRequest{
		Id:      "stellar" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
		Payload: wrapped,
		Method:  "WriteReport",
	}), func(i *sdkpb.CapabilityResponse) (*WriteReportReply, error) {
		switch payload := i.Response.(type) {
		case *sdkpb.CapabilityResponse_Error:
			return nil, caperrors.DeserializeErrorFromString(payload.Error)
		case *sdkpb.CapabilityResponse_Payload:
			output := &WriteReportReply{}
			err = payload.Payload.UnmarshalTo(output)
			return output, err
		default:
			return nil, errors.New("unexpected response type")
		}
	})

	return capCallResponse

}

type ClientRestrictor struct {
	ChainSelector uint64
}

func (c *ClientRestrictor) LimitGetLatestLedger(maxCalls int32) *sdkpb.CapabilityRestriction {
	return &sdkpb.CapabilityRestriction{
		Restriction: &sdkpb.CapabilityRestriction_Method{
			Method: &sdkpb.MethodRestriction{
				Id:       "stellar" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
				Method:   "GetLatestLedger",
				MaxCalls: maxCalls,
			},
		},
	}
}

func (c *ClientRestrictor) LimitReadContract(maxCalls int32) *sdkpb.CapabilityRestriction {
	return &sdkpb.CapabilityRestriction{
		Restriction: &sdkpb.CapabilityRestriction_Method{
			Method: &sdkpb.MethodRestriction{
				Id:       "stellar" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
				Method:   "ReadContract",
				MaxCalls: maxCalls,
			},
		},
	}
}

func (c *ClientRestrictor) LimitWriteReport(maxCalls int32) *sdkpb.CapabilityRestriction {
	return &sdkpb.CapabilityRestriction{
		Restriction: &sdkpb.CapabilityRestriction_Method{
			Method: &sdkpb.MethodRestriction{
				Id:       "stellar" + ":ChainSelector:" + strconv.FormatUint(c.ChainSelector, 10) + "@1.0.0",
				Method:   "WriteReport",
				MaxCalls: maxCalls,
			},
		},
	}
}

const StellarMainnet = 17783245649066640917

const StellarTestnet = 4894814558906953166

func ChainSelectorFromName(name string) (uint64, error) {
	switch name {
	case "stellar-mainnet":
		return StellarMainnet, nil
	case "stellar-testnet":
		return StellarTestnet, nil
	default:
		return 0, errors.New("unknown ChainSelector" + name)
	}
}
